version: 2
updates:
  - directory: /
    package-ecosystem: npm
    schedule:
      interval: daily
    groups:
      vuepress:
        patterns:
          - "vuepress-vite"
          - "@vuepress/*"
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily

  - directory: /infra
    package-ecosystem: terraform
    schedule:
      interval: daily